MONGODB_HOST: mongodb.dsoaws.fun
REDIS_HOST: redis.dsoaws.fun
CATALOGUE_HOST: catalogue.dsoaws.fun
CART_HOST: cart.dsoaws.fun
USER_HOST: user.dsoaws.fun
RABBITMQ_HOST: rabbitmq.dsoaws.fun
MYSQL_HOST: mysql.dsoaws.fun
SHIPPING_HOST: shipping.dsoaws.fun
PAYMENT_HOST: payment.dsoaws.fun